spring:
  datasource:
    username: root
 ##   password: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
   ## url: jdbc:mysql://120.55.96.180:3306/ly_exepert?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    url: jdbc:mysql://localhost:3306/ly?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
        0
      max-file-size:
        500MB
      max-request-size:
        500MB
server:
  port: 9876
  servlet:
    context-path: /LY
logging:
  level:
    com.yy.spring.dao: debug
mybatis:
  type-aliases-package: com.ly.spring.entity
  mapper-locations:
  - classpath:mapper/*.xml
